In [3]:
import cv2
from ultralytics import YOLO
from utils.bbox_area import bbox_area

In [4]:
model = YOLO("models/yolov8m.pt")
# model in multi_people_splitting/

In [13]:
def test_object_detection(path, show=False):
    # frame = cv2.imread(path)[:, 300:]
    frame = cv2.imread(path)

    results = model(frame)
    bboxes = []
    # Render the results
    for result in results:
        if result.boxes is not None:
            for box in result.boxes:
                label = model.names[int(box.cls[0])]
                confidence = box.conf[0]
                if label == "person" and confidence > 0:
                    bbox = box.xyxy[0].numpy().astype(int)
                    # print(bbox)
                    if len(bboxes) == 4:
                        break
                    if bbox_area(bbox) < 40000:
                        continue
                    bboxes.append(bbox)
                    x1, y1, x2, y2 = bbox

                    # Draw bounding box and label
                    cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
                    cv2.putText(
                        frame,
                        f"{label} {confidence:.2f}",
                        (x1, y1 - 10),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.5,
                        (0, 255, 0),
                        2,
                    )
    while show:
        cv2.imshow("C", frame)
        if cv2.waitKey(10) & 0xFF == ord("q"):
            cv2.destroyAllWindows()
            break

    return frame, bboxes

In [28]:
path = "/home/hassaan/Downloads/train_2500/images_final/285.png"
# path = "/home/hassaan/Downloads/allFinal/091363275.jpg"
# path = "/home/hassaan/Downloads/allFinal/111.png"
# path = "/home/hassaan/Downloads/PoseDetection/folder1/content/hosp11.jpg"

In [30]:
image, bboxes = test_object_detection(path, show=True)

0: 384x640 5 persons, 968.9ms
Speed: 4.1ms preprocess, 968.9ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)


In [31]:
bboxes

[array([ 976,  173, 1114,  519]), array([ 96, 142, 245, 440])]

In [10]:
for i in range(len(bboxes)):
    print(bboxes[i])
    x1, y1, x2, y2 = bboxes[i]
    cropedImage = image[y1:y2, x1:x2]
    while True:
        cv2.imshow(f"{i} image: ", cropedImage)

        if cv2.waitKey(10) & 0xFF == ord("q"):
            break
    cv2.destroyAllWindows()

[535 143 633 361]
[416 157 489 349]
[362 119 438 337]


In [85]:
cv2.destroyAllWindows()

In [29]:
approved = 0
disapproved = 0

In [79]:
while True:
    # Display the frame
    h, w, _ = image.shape
    # print(h, w)
    # image = cv2.resize(image, (321 * 3, 491 * 3))
    cv2.imshow("yeich", image)
    # plt.imshow(img)
    # print("worked")
    cv2.imwrite("/home/hassaan/Downloads/asdfDepth.png", image)
    # Exit on 'q' key press
    if cv2.waitKey(10) & 0xFF == ord("q"):
        break
cv2.destroyAllWindows()

In [ ]:
for i in range(0, 10):

    fullPath = path + str(i) + ".png"
    print(fullPath)
    image = test_object_detection(fullPath)

    for bbox in bboxs:
        
        image = image[x1:,:]

    while True:
        # Display the frame
        h, w, _ = image.shape
        # print(h, w)
        # image = cv2.resize(image, (321 * 3, 491 * 3))
        cv2.imshow("YOLOv8 Nano", image)
        # plt.imshow(img)
        # print("worked")
        cv2.imwrite("/home/hassaan/Downloads/asdfDepth.png", image)
        # Exit on 'q' key press
        if cv2.waitKey(10) & 0xFF == ord("q"):
            approved += 1
            break
        if cv2.waitKey(10) & 0xFF == ord("p"):
            disapproved += 1
            break
    cv2.destroyAllWindows()

print("approved :", approved)
print("disapproved :", disapproved)

In [18]:
for i in range(0, 50):
    path = f"/home/hassaan/Downloads/DPT2/{i}.png"

    test_object_detection(path, show=True)


0: 384x640 1 person, 2578.5ms
Speed: 126.4ms preprocess, 2578.5ms inference, 16.1ms postprocess per image at shape (1, 3, 384, 640)
[799 100 885 309]

0: 480x640 1 person, 1643.2ms
Speed: 7.4ms preprocess, 1643.2ms inference, 3.4ms postprocess per image at shape (1, 3, 480, 640)
[492 160 723 439]

0: 384x640 3 persons, 1140.2ms
Speed: 5.6ms preprocess, 1140.2ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)
[ 763    2 1280  705]
[265 251 417 503]

0: 384x640 3 persons, 1175.2ms
Speed: 8.0ms preprocess, 1175.2ms inference, 5.7ms postprocess per image at shape (1, 3, 384, 640)
[ 875  289 1022  613]
[  0   5 470 706]
[526 218 788 710]

0: 416x640 1 person, 1314.1ms
Speed: 5.4ms preprocess, 1314.1ms inference, 1.6ms postprocess per image at shape (1, 3, 416, 640)

0: 384x640 2 persons, 1279.3ms
Speed: 4.6ms preprocess, 1279.3ms inference, 12.6ms postprocess per image at shape (1, 3, 384, 640)
[511 192 563 414]

0: 384x640 1 person, 1122.3ms
Speed: 7.0ms preprocess, 1122.

KeyboardInterrupt: 

In [19]:
cv2.destroyAllWindows()